name: Demo Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  ios-demos:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme:
          - BenchmarkIPhone
          - CaptureASL
          - RegisteredLoggingTest (Mobile)
          - TextXcodeColors (Mobile)
          - UniversalApp
          - WebServerIPhone
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: Demos/Demos.xcworkspace
          scheme: ${{matrix.scheme}}
          configuration: Release
          sdk: iphonesimulator
          action: build

  macos-demos:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme:
          - BenchmarkIPhone
          - BenchmarkMac
          - CLI
          - ContextFilter
          - CoreDataLogger
          - CustomFormatters
          - CustomLogLevels
          - DispatchQueueLogger
          - FineGrainedLogging
          - GlobalLogLevel
          - LogFileCompressor
          - NonArcTest
          - OverflowTestMac
          - PerUserLogLevels
          - RegisteredLoggingTest (Desktop)
          - RollingTestMac
          - SQLiteLogger
          - TestXcodeColors (Desktop)
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: Demos/Demos.xcworkspace
          scheme: ${{matrix.scheme}}
          configuration: Release
          action: build
