name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  static-lib:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: ^12.5
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: Integration/Integration.xcodeproj
          scheme: iOSStaticLibraryIntegration
          configuration: Release
          action: build

  dynamic-lib:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme:
          - macOSSwiftIntegration
          - iOSFrameworkIntegration
          - tvOSSwiftIntegration
        destination: ['']
        include:
          - scheme: watchOSSwiftIntegration
            destination: 'platform=iOS Simulator,name=iPhone 11 Pro'
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: ^12.5
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: Integration/Integration.xcodeproj
          scheme: ${{matrix.scheme}}
          configuration: Release
          destination: ${{matrix.destination}}
          action: build
        # watchOS builds seems to fail as of Xcode 11.4...
        continue-on-error: ${{matrix.scheme == 'watchOSSwiftIntegration'}}
