name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  static-lib:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: [iOSStaticLibraryIntegration]
        sdk: [iphonesimulator]
        destination: []
        build-settings: ['PLATFORM_NAME=iphonesimulator']
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: Integration/Integration.xcodeproj
          scheme: ${{matrix.scheme}}
          configuration: Release
          sdk: ${{matrix.sdk}}
          destination: ${{matrix.destination}}
          build-settings: ${{matrix.build-settings}}
          action: build

  dynamic-lib:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: []
        sdk: []
        destination: []
        build-settings: []
        include:
          - scheme: macOSSwiftIntegration
            sdk: macosx
            destination: ''
            build-settings: ''
          - scheme: iOSFrameworkIntegration
            sdk: iphonesimulator
            destination: ''
            build-settings: 'PLATFORM_NAME=iphonesimulator'
          - scheme: tvOSSwiftIntegration
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
            build-settings: ''
          - scheme: watchOSSwiftIntegration
            sdk: watchsimulator
            destination: 'platform=iOS Simulator,name=iPhone 11 Pro'
            build-settings: ''
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: Integration/Integration.xcodeproj
          scheme: ${{matrix.scheme}}
          configuration: Release
          sdk: ${{matrix.sdk}}
          destination: ${{matrix.destination}}
          build-settings: ${{matrix.build-settings}}
          action: build
