name: Library Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  static-lib:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - sdk: iphonesimulator
            build-settings: 'PLATFORM_NAME=iphonesimulator'
          - sdk: macosx
            build-settings: ''
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: Xcode/Lumberjack.xcworkspace
          scheme: CocoaLumberjack-Static
          configuration: Release
          sdk: ${{matrix.sdk}}
          build-settings: ${{matrix.build-settings}}
          action: build

  dynamic-lib:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: [CocoaLumberjack, CocoaLumberjackSwift]
        sdk: [iphonesimulator, macosx, watchsimulator]
        destination: ['']
        include:
          - scheme: CocoaLumberjack
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4'
          - scheme: CocoaLumberjackSwift
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4'
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: Xcode/Lumberjack.xcworkspace
          scheme: ${{matrix.scheme}}
          configuration: Release
          sdk: ${{matrix.sdk}}
          destination: ${{matrix.destination}}
          action: build
