name: Library Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  static-lib:
    runs-on: macos-12
    strategy:
      matrix:
        sdk: [iphonesimulator, macosx]
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: ^12.4
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: Xcode/Lumberjack.xcworkspace
          scheme: CocoaLumberjack-Static
          configuration: Release
          sdk: ${{matrix.sdk}}
          action: build

  dynamic-lib:
    runs-on: macos-12
    strategy:
      matrix:
        scheme: [CocoaLumberjack, CocoaLumberjackSwift]
        sdk: [iphonesimulator, macosx, watchsimulator, appletvsimulator]
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: ^12.4
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: Xcode/Lumberjack.xcworkspace
          scheme: ${{matrix.scheme}}
          configuration: Release
          sdk: ${{matrix.sdk}}
          action: build
