name: Validations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  validate-cocoapods:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - run: pod lib lint

  run-danger:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: danger/swift@3.3.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
