name: Validations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

defaults:
  runs-on: macos-latest

jobs:
  validate-cocoapods:
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - run: pod lib lint

  run-danger:
    if: github.event == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - run: ./Scripts/ci-select-xcode.sh
      - run: bundle exec danger
